# Generated by Django 4.2.3 on 2023-07-21 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo_cad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
